### ISSUE TITLE
Add Aliucord/Teamworking Tools & Video Conferencing

### ISSUE THREAD

**Issue by MatadorProBr** [pluja/awesome-privacy#134]
### Aliucord

* [Aliucord](https://github.com/Aliucord/Aliucord) - A modification for the Android Discord app inspired by desktop client modifications.
* **License**: [OSL-3.0](https://github.com/Aliucord/Aliucord/blob/main/LICENSE)
* **Why do you think this helps users privacy?**: Because Aliucord removes all of the [Discord telemetry and tracking](https://github.com/Aliucord/Aliucord/blob/main/Aliucord/src/main/java/com/aliucord/coreplugins/NoTrack.java).
* **Under what section should this service be listed?**: Maybe Teamworking Tools and Video Conferencing.
* **Additional comments / info**: N/A

**Comment by pluja** [comment]
Can you provide the commit where the Telemetry is removed or some kind of evidence? This is not stated in the project description and I couldn't find any evidence of it. Thank you.

**Comment by MatadorProBr** [comment]
> Can you provide the commit where the Telemetry is removed or some kind of evidence? This is not stated in the project description and I couldn't find any evidence of it. Thank you.

https://github.com/Aliucord/Aliucord/blob/main/Aliucord/src/main/java/com/aliucord/coreplugins/NoTrack.java

**Comment by NSABackdoors** [comment]
@pluja

Any reasons as to why this hasn't been closed? [Aliucord has already been added under Alternative Discord clients](https://github.com/pluja/awesome-privacy/commit/ae0ef7045487094218d8edd396aed28c809dadf6).

**Comment by MatadorProBr** [comment]
I forgot to close this issue so I will close now.

Also it seems "Aliucord" is writed wrong.
