### ISSUE TITLE
wrong Information about Aurora Droid 

### ISSUE THREAD

**Issue by phildev4** [pluja/awesome-privacy#151]
The repo says ` Aurora Droid - Aurora Droid is a modern FOSS client for F-Droid.` when in fact it is a FOSS client for the google play store

**Comment by itsmeboy0** [comment]
No.

> - Aurora Droid - Aurora Droid is a modern FOSS client for F-Droid.
> - Aurora Store - Aurora Store is an open-source alternative Google Play Store frontend client with privacy and modern design in mind.

**Aurora Store** is the Google Play Store Client and the information listed is correct.

**Comment by pluja** [comment]
Aurora Droid is a F-Droid client as @itsmeboy0 says.

**Comment by phildev4** [comment]
Sorry by bad
