### ISSUE TITLE
Add CTemplar

### ISSUE THREAD

**Issue by NSABackdoors** [pluja/awesome-privacy#172]
### Service Name
* [CTemplar](https://ctemplar.com) - Secure and Encrypted Email based in Iceland
* **License**: Android and Webclient appear to be licensed under Apache 2.0 although the back end seems to be proprietary.
* **Why do you think this helps users privacy?**: It's an encrypted email service similar to ProtonMail and Tutanota that allows for encrypted communication using email.
* **Under what section should this service be listed?**: Mail Services
* **Additional comments / info**: CTemplar was recently added to [PrivacyGuides](https://github.com/privacyguides/privacyguides.org/pull/292) and if you have any questions/in need of further insight then I suggest reading the disucssions they had with the founder.

**Comment by BobIsMyManager** [comment]
CTemplar is now shut down, might aswell close this issue.

**Comment by pluja** [comment]
Closing as Ctemplar is shutting down:
https://ctemplar.com/ctemplar-is-shutting-down/
