### ISSUE TITLE
imgin.voidnet.tech is down

### ISSUE THREAD

**Issue by i13e** [pluja/awesome-privacy#196]
From `ping`: 
```
ping imgin.voidnet.tech
PING imgin.voidnet.tech(2001:19f0:5c01:197c:5400:3ff:fedc:5c00 (2001:19f0:5c01:197c:5400:3ff:fedc:5c00)) 56 data bytes
^C
--- imgin.voidnet.tech ping statistics ---
80 packets transmitted, 0 received, 100% packet loss, time 80059ms
```
I'm not sure how long it's been down (main site, https://voidnet.tech, is still up), are there any alternatives to imgin out there that are more reliable?

**Comment by pluja** [comment]
You can use rmigo:
https://codeberg.org/video-prize-ranch/rimgo

I will be listing it soon
