### ISSUE TITLE
[NSP] Nitter

### ISSUE THREAD

**Issue by 1hiking** [pluja/awesome-privacy#2]
### Nitter

* [Nitter](https://nitter.net/) - Nitter is a free and open source alternative Twitter front-end focused on privacy.
* **License**: AGPL v3.0
* **Why do you think this helps users privacy?**: It allows users to be able to browse twitter without having to conect to their servers. Most features also work without Javascript (except playing videos)
* **Under what section should this service be listed?**: Twitter
* **Additional comments / info**: Nope, have a nice day

**Comment by 1hiking** [comment]
Forgot to mention but here is their [repo](https://github.com/zedeus/nitter) and there are more [instances](https://github.com/zedeus/nitter/wiki/Instances)!

**Comment by pluja** [comment]
Added!
