### ISSUE TITLE
DeepL declared bad without explanation 

### ISSUE THREAD

**Issue by einekratzekatze** [pluja/awesome-privacy#214]
DeepL is by far the most accurate translator. It is even open source iirc. Why is it on "dont use"?

**Comment by pluja** [comment]
Hi! I can provide information about why DeepL is bad in my opinion. Then, with the provided information, we can discuss in this issue if it is bad or not. Here we go. 

From [their privacy policy](https://www.deepl.com/en/privacy):

#### 1. DeepL states that you should only enter data that you want to be transmitted to their servers:

> When using our translation service, please only enter texts that you wish to transfer to our servers. 

Specifically it states that:

> Please note that according to its Terms and Conditions, you may not use DeepL Translator for the translation of texts containing personal data of any kind. 

#### 2. DeepL stores automatically some data from their users:

> Regardless of whether you use our paid or free service, your device automatically transmits certain data for technical reasons when you access our website [www.deepl.com](https://www.deepl.com/). The following data that you may send us will be stored:   

    Date and time of access
    Browser type and version
    Operating system
    URL of the website previously visited
    Volume of data transmitted
    Requested domain
    Search term when using a web browser
    Full IP address
    Diagnostic information in the event of errors

From their [Terms of Service](https://www.deepl.com/en/pro-license?tab=pro) of the Pro version:

> 3.1.3 DeepL will only access the Content and/or the Processed Content in the event and to the extent required to carry out a diagnosis and to solve technical issues which may eventually compromise the availability of the service. To the extent required for the purposes mentioned above and in derogation from Section 3.1.2 DeepL may, in exceptional cases, automatically store Content and/or Processed Content for a maximum period of 72 hours in case certain error patterns occur during the processing of the translation request. The Content and/or the Processed Content will be stored in an encrypted form for the duration of the debugging process and will be automatically deleted afterwards. The access to the cryptographic keys for the decryption of the Contents and/or of the Processed Contents will only be granted in individual cases in the context of a logged process for selected employees of DeepL who are bound to secrecy and after the access has been approved by the company management. The Contents and/or Processed Contents stored for debugging purposes will not be linked to any individual Customer.
