### ISSUE TITLE
Add PrivateBin/Online Pastebin

### ISSUE THREAD

**Issue by heywolf15** [pluja/awesome-privacy#226]
### PrivateBin

* [PrivateBin](https://github.com/PrivateBin/PrivateBin) - Online Pastebin.
* **License type**: GPLv2
* **Why do you think this helps users privacy?**: open source online [pastebin](https://en.wikipedia.org/wiki/Pastebin) where the server has zero knowledge of pasted data
* **Under what section should this service be listed?**: Self-Hosted Services
* **Additional comments / info**: fork of ZeroBin

**Comment by heywolf15** [comment]
Is this being ignore or what?
For who want to check more curated list of privacy & security [https://github.com/Lissy93/awesome-privacy](url)

**Comment by pluja** [comment]
Not being ignored, I will add them when I have time to. You can add a PR if you want this to be added quicker
