### ISSUE TITLE
Add  [No-Chat-Reports]/[Games -> Minecraft]

### ISSUE THREAD

**Issue by ghost** [pluja/awesome-privacy#230]
### Service Name

* [No-Chat-Reports](https://github.com/Aizistral-Studios/No-Chat-Reports) - Strips cryptographic signatures from player messages, making it impossible to track and associate them with your Mojang/Microsoft account.
* **License**: WTFPL license (Public domain equivalent)
* **Why do you think this helps users privacy?**: It allows players to have cryptographic deniability over the messages they sent, stopping messages being permanently linked to your Microsoft account
* **Under what section should this service be listed?**: Games -> Minecraft -> Modifications.
* **Additional comments / info**: Requires a mod loader like [Forge](https://github.com/MinecraftForge/MinecraftForge) or [Fabric](https://github.com/FabricMC/fabric) to function. It also makes [No Telemetry](https://github.com/kb-1000/no-telemetry) mod redundant, as it's features are part of this mod. The fact these signatures are enabled from 1.19 onwards should probably be mentioned under the minecraft section.

**Comment by pluja** [comment]
Added!
