### ISSUE TITLE
Consider merging with an existing list

### ISSUE THREAD

**Issue by Jogai** [pluja/awesome-privacy#24]
It look like @kevincolemaninc's list (https://github.com/KevinColemanInc/awesome-privacy) exists longer. Why not contribute to that?

**Comment by MonsieurBibo** [comment]
It seems to be a good option, however that repo doesn't seem to be really maintained anymore.

**Comment by Jogai** [comment]
Its fairly normal to see the activity slump after a while in an awesome list, because real awesome resources are becoming scarce after a while. That said, last commit was 2 months ago, which is not that long ago. If you reach out, maybe you can be a co-maintainer. Then you're sure its maintained again :smile:

**Comment by KevinColemanInc** [comment]
My list is still alive! I accept/reject PRs when they come through. The two recent ones I need to do more research before I feel comfortable merging them in.
