### ISSUE TITLE
WikiLess source code link returns a 404

### ISSUE THREAD

**Issue by ndvarn** [pluja/awesome-privacy#262]
Same as title: as of the time of writing this, the link to the source code of WikiLess (the wikipedia alternative) results in a 404.

**Comment by pluja** [comment]
Wikiless needs to be removed. The project seems to have been removed by Codeberg for some reason. You can read more about it here:

On reddit: https://td.r3d.red/r/PrivacyGuides/comments/xwm7o3/wikiless_repository_deleted/
And on the dev site: https://orenom.fi/

I will remove it temporarly until this is solved.

**Comment by RokeJulianLockhart** [comment]
[`Metastem/Wikiless`](https://github.com/Metastem/Wikiless/blob/b76805f86fef45bc49c76516e1fb3d362acefebb/README.md?plain=1#L5C21-L5C100:~:text=!%5Bhidden_dimension%5D(-,https://github.com/user%2Dattachments/assets/4093053d%2Da7c4%2D45aa%2D8860%2Dea0f64a841e9,-)) now exists. [^1]

[^1]: [`reddit.com/r/PrivacyGuides/comments/xwm7o3/comment/no6wk35`](https://www.reddit.com/r/PrivacyGuides/comments/xwm7o3/comment/no6wk35/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
