### ISSUE TITLE
Replace Decentraleyes by LocalCDN

### ISSUE THREAD

**Issue by princess-mikus** [pluja/awesome-privacy#273]
Decentraleyes has not been updated in almost a year and I heard development has stopped. LocalCDN can do exactly the same but it's updated way more often. It even passes Decentraleyes testing utility.

**Comment by monokrome** [comment]
![image](https://user-images.githubusercontent.com/242997/199316406-16c9ec3d-fd10-44c1-8e59-07db517c0b02.png)

**Comment by monokrome** [comment]
![image](https://user-images.githubusercontent.com/242997/199316542-66f78e01-5a6d-4cee-a683-d3b5765249a7.png)
