### ISSUE TITLE
Add Trace browser addon

### ISSUE THREAD

**Issue by BardiaB8** [pluja/awesome-privacy#306]
### Trace

* [Trace](https://github.com/jake-cryptic/AbsoluteDoubleTrace/) - protects the user against common browser fingerprinting methods.
* **Why do you think this helps users privacy?**: randomizes and hides some information that can be used for browser fingerprinting.
* **Under what section should this service be listed?**: browser addons

**Comment by monokrome** [comment]
This project seems unmaintained for over a year now
