### ISSUE TITLE
Link in wikipedia section return a 404 error

### ISSUE THREAD

**Issue by Yann-Plougonven** [pluja/awesome-privacy#339]
Hi !

The link [Wikiless manifesto](https://codeberg.org/orenom/wikiless#why-i-should-use-wikiless-instead-of-wikipedia) in the wikipedia section (https://github.com/pluja/awesome-privacy#wikipedia) returnd a 404 error.

**Comment by supleed2** [comment]
Looks like this was brought up in #262 but only the line mentioning the alternative was updated in https://github.com/pluja/awesome-privacy/commit/182198f2776e9526024f3b3828ef0f37b9e90f61, and not the link to the manifesto hosted at the same repository.

**Comment by pluja** [comment]
True, maybe we should contact [orenom](https://orenom.fi) (the maintainer) to ask for the source code, as I can't find where is hosted
