### ISSUE TITLE
Add Proton Pass

### ISSUE THREAD

**Issue by NixyJuppie** [pluja/awesome-privacy#346]
### Proton Pass

* [Proton Pass](https://proton.me/pass) - Open-source and encrypted password manager
* **License**: GPL 3.0
* **Why do you think this helps users privacy?**: It's open source, encrypted, and made by Proton, which has a good history of respecting user privacy (makers of ProtonMail and ProtonDrive).
* **Under what section should this service be listed?**: Password Managers
* **Additional comments / info**: <Add any additional info here>

**Comment by mjesusoj** [comment]
I hope Proton Pass includes on the list, it's very intuitive and the design beautiful as Proton's ecosystem.

Also, I think it's better than Bitwarden on autocomplate, security and privacy 👏👏

**Comment by NixyJuppie** [comment]
Proton Pass has passed an independent security audit
https://proton.me/blog/pass-open-source-security-audit
