### ISSUE TITLE
Add LinkStack/Link In Bio Tools

### ISSUE THREAD

**Issue by HPOA909** [pluja/awesome-privacy#350]
### LinkStack

* [LinkStack](https://linkstack.org/) - LinkStack is a highly customizable link sharing platform with an intuitive, easy to use user interface.
* **License**: AGPL v3
* **Why do you think this helps users privacy?**: This is fully self-hostable and customizable with your needs.
* **Under what section should this service be listed?**: Link in bio tools
* **Additional comments / info**: none

**Comment by JulianPrieber** [comment]
Dint know this existed, I think this would be a great match 👍

**Comment by HPOA909** [comment]
You have found me!
