### ISSUE TITLE
Add Penpot/Uncategorized

### ISSUE THREAD

**Issue by Helenaria** [pluja/awesome-privacy#356]
### Penpot
* [Penpot](https://penpot.app/) - Penpot is the Open-Source Design & Prototyping Tool for Product Teams.
* **License**: <Mozilla Public License, v. 2.0>
* **Why do you think this helps users privacy?**: <You can deploy your own instance with it, and dev recently updated local cache for google fonts. Open source as well>
* **Under what section should this service be listed?**: <Uncategorized, or Teamwork>
* **Additional comments / info**: <Github documentation here: https://github.com/penpot/penpot>

**Comment by pluja** [comment]
Isn't penpot an alternative to Figma? Maybe we could add a new section "Design tools" or something like that and add Penpot there?

**Comment by Helenaria** [comment]
Yeah, that works too. I do know of a few other open source design tools to recommend so having a Design Tools section would help!
