### ISSUE TITLE
Add Inkscape/Design Tools

### ISSUE THREAD

**Issue by Helenaria** [pluja/awesome-privacy#357]
### Inkscape

* [Inkscape](https://inkscape.org/) - <Inkscape is a Free and open source [vector graphics editor](http://en.wikipedia.org/wiki/Comparison_of_vector_graphics_editors) for GNU/Linux, Windows and macOS. It offers a rich set of features and is widely used for both artistic and technical illustrations such as cartoons, clip art, logos, typography, diagramming and flowcharting. It uses [vector graphics](http://en.wikipedia.org/wiki/Vector_graphics) to allow for sharp printouts and renderings at unlimited resolution and is not bound to a fixed number of pixels like raster graphics. Inkscape uses the standardized [SVG file format](http://www.w3.org/Graphics/SVG/) as its main format, which is supported by many other applications including web browsers.>
* **License**: GPL
* **Why do you think this helps users privacy?**: <Open source, free to use, doesnt sell info. Inkscape is a member of the Software Freedom Conservancy, a US 501(c)(3) non-profit organization, no affiliation with bigtech,[ Privacy Policy](https://inkscape.org/about/privacy/) here>
* **Under what section should this service be listed?**: Design Tools
* **Additional comments / info**: <It's considered a replacement for Adobe Illustrator, alongside GIMP and GNU Image Manipulation Program>

**Comment by supleed2** [comment]
It's already listed under [Photo Editing and Management](https://github.com/pluja/awesome-privacy#photo-editing-and-management), alongside GIMP and others?

**Comment by Helenaria** [comment]
Oh no, I didn't notice! thank you for pointing that out!
