### ISSUE TITLE
Add Android File Browsers Section

### ISSUE THREAD

**Issue by Splarkszter** [pluja/awesome-privacy#376]
* **Why do you think this helps users privacy?**:
There are many many many file browsers out there, some have useful features like FTP server, Favorites, Root Access, Compressed file formats support.

Having reliable apps for that would be awesome!

**Comment by meatspinner** [comment]
Its right there:
https://github.com/pluja/awesome-privacy#android-file-manager

**Comment by Splarkszter** [comment]
how i didn't find it?.

ha. thanks.
