### ISSUE TITLE
Add [Picocrypt]/[Encryption]

### ISSUE THREAD

**Issue by InterMob** [pluja/awesome-privacy#38]
### Picocrypt
* [Picocrypt](https://github.com/HACKERALERT/Picocrypt/) - Picocrypt is a very small (hence "Pico"), very simple, yet very secure file encryption tool. 
* **License**:  GPL-3.0 License 
* **Why do you think this helps users privacy?**: It's infinitely easier to use than VeraCrypt, Picocrypt is portable and tiny (just 4MB for Windows!), Picocrypt supports anti-corruption through Reed-Solomon and file integrity checking through Poly1305.
* **Under what section should this service be listed?**: Section Encryption
* **Additional comments / info**: Picocrypt for Debian-based linux distros is "coming soon" also, there's an outdated and useless piece of abandonware called PicoCrypt on the Internet, which was last updated in 2005. PicoCrypt is not related to Picocrypt (this project).

**Comment by pluja** [comment]
Just messed around a bit with it on a Windows VM, looks neat. Added!
