### ISSUE TITLE
Operating Systems/Smart TV section is misleading

### ISSUE THREAD

**Issue by Clozent** [pluja/awesome-privacy#388]
From the [Smart TV section](https://github.com/pluja/awesome-privacy#smart-tv):

> Don't use Android TV, LG WebOS or any other privacy-invasive common TV OS that comes preinstalled with your TV.

The options given in the following list are not all TV Operating Systems, specifically Kodi and Jellyfin's front-end, which are just apps (Jellyfin is used to host content and access it from elsewhere with a neat front-end). Kodi has [LibreELEC](https://libreelec.tv/), though, but it's primarily available for TV boxes (and some Samsung devices).

The section says not to use LG WebOS and Android TV, when none of the listed "alternatives" are available for LG TVs or Android smart TVs (excluding TV boxes).

Also, it appears that RaspberryCast has been archived for over a year now (since September 12th, 2022), with it's last commit being on October 18th, 2018.

### Summarry:

1. Kodi is an app, and not an operating system (there is LibreELEC, but it's not really available for smart TVs).
2. Jellyfin is a server-side program with a front-end app, and not an operating system.
3. OSMC _does_ actually seem to be an operating system, but it is only available for three brands of TV _boxes_, according to their download page:
    - Raspberry Pi (Pi 1, 2, 3, 3+, 4/400 & Zero)
    - Vero (OSMC's flagship device)
    - Apple TV (Only the 1st generation)
4. RaspberryCast is no longer maintained, and should probably not be used.

**Comment by pluja** [comment]
Hey, thank you for all this info, do you have any suggestion for a SmartTV OS alternative?

Maybe it would be better to say that using a RaspberryPi connected to the tv with something like KDEConnect for remote controlling, Kodi and Jellyfin would be better?

**Comment by pluja** [comment]
I have added an update, please @Clozent tell me if that is clearer or any better

**Comment by Clozent** [comment]
Yes, the section is now clearer and better overall, thank you!
I am unfortunately unaware of any SmartTV OS alternatives, though. Hopefully something will pop up eventually!

**Comment by meatspinner** [comment]
There's KDE Plasma Big Screen, which is apparently a Shell/Launcher you can use on your TV.
