### ISSUE TITLE
Remove Ravio OTP

### ISSUE THREAD

**Issue by hankertrix** [pluja/awesome-privacy#398]
Ravio OTP has been acquired by a sketchy company called Mobime, and the privacy and security of the app may have been compromised. It is best to no longer recommend them as a 2FA app.

https://github.com/raivo-otp/marketing-website/issues/19

https://github.com/raivo-otp/ios-application/issues/285

https://github.com/raivo-otp/ios-application/issues/271

**Comment by ttollet** [comment]
Most recent issue:
https://news.ycombinator.com/item?id=40523411

It seems Raivo should have been removed long ago.

**Comment by hankertrix** [comment]
They have also either deleted or blocked access to all issues on their repositories to try to hide this, which is a massive red flag.

Please remove it as soon as possible.

**Comment by hankertrix** [comment]
Closing as pull request #445 has been merged.
