### ISSUE TITLE
[NSP] Aether

### ISSUE THREAD

**Issue by spencerhadley** [pluja/awesome-privacy#4]
### Aether
* [Aether](https://getaether.net) Ephemeral P2P Public Communities
* **License**: <AGPL-3.0>
* **Why do you think this helps users privacy?**: < anonymous names, posts disappear after six months >
* **Under what section should this service be listed?**: < Reddit >
* **Additional comments / info**: <Add any additional info here>

**Comment by pluja** [comment]
Added!
