### ISSUE TITLE
Add [Simple File Manager]/[Android File Manager]

### ISSUE THREAD

**Issue by guglovich** [pluja/awesome-privacy#405]
### Service Name

* [Simple File Manager](https://github.com/SimpleMobileTools/Simple-File-Manager) 
* **License**: GPL v.3.0
* **Why do you think this helps users privacy?**: Open license
* **Under what section should this service be listed?**: Android File Manager
* **Additional comments / info**: The developer has a whole suite of applications

**Comment by polyzen** [comment]
https://github.com/SimpleMobileTools/General-Discussion/issues/241
https://github.com/SimpleMobileTools/General-Discussion/issues/244

**Comment by polyzen** [comment]
Forgot about this: https://github.com/pluja/awesome-privacy/issues/399
