### ISSUE TITLE
Remove all current Android(/iOS) "Privacy respecting Reddit clients": Slide, Infinity, Dawn

### ISSUE THREAD

**Issue by coren-frankel** [pluja/awesome-privacy#427]
Due to Reddit's dramatic API pricing change in 2023, these apps have struggled to maintain themselves. 

Infinity persists, but they have added a paid version of the app, and the free version has taken on ads and pop-ups to compensate for the paywall. Perhaps keeping Infinity, and noting the change would be best.

**Comment by pluja** [comment]
added [redlib](https://github.com/redlib-org/redlib) and removed other clients. thanks for the heads-up!
