### ISSUE TITLE
Broken link to PrivacyGuides

### ISSUE THREAD

**Issue by NewGuy103** [pluja/awesome-privacy#461]
The link https://www.privacyguides.org/android/overview// shows a blank page, checking console shows that the link is a 404. Removing the two slashes redirects you to the page https://www.privacyguides.org/en/os/android-overview/

The [GitHub Page](https://pluja.github.io/awesome-privacy/) also shows the broken link.

Going to https://www.privacyguides.org/android/overview/ or https://www.privacyguides.org/android/overview// causes a 404 to be shown, but going to https://www.privacyguides.org/android/overview will redirect you to the intended page.
![image](https://github.com/user-attachments/assets/1981cabc-7efa-4fc2-a46f-34cba1256ad8)

**Comment by pluja** [comment]
fixed, thanks!
