### ISSUE TITLE
Add Notesnook to Notes & Tasks

### ISSUE THREAD

**Issue by thecodrr** [pluja/awesome-privacy#56]
### Notesnook

* [Notesnook](https://notesnook.com/) - A simple and private note taking app that encrypts everything on your device.
* **License**: Not open source
* **Why do you think this helps users privacy?**: It is zero-knowledge i.e. everything gets encrypted on your device (browser or mobile), has no trackers or ads, and works on almost every platform out there.
* **Under what section should this service be listed?**: Notes & Tasks
* **Additional comments / info**: There is a free basic plan and a Pro plan with 14-day free trial.

**Comment by pluja** [comment]
I like it. I think that, event it is not open source it is a good app and makes a lot of privacy claims. I will let it sit here for a while, if anyone knows anything aobut this app/developers I would love to hear more info. 

I will try it out, for now I installed the APK and it contains no trackers; also the website has no trackers.

**Comment by thecodrr** [comment]
@pluja I am the developer and founder behind it. You can ask me any questions.

**Comment by monokrome** [comment]
It is only my opinion, but software that does not provide an open source client can not prove that they respect user privacy and should not be considered. Any recommendation of such software is optimistic at best.

**Comment by thecodrr** [comment]
> but software that does not provide an open source client can not prove that they respect user privacy

I disagree. While the majority believes that Open Source = Privacy, it is true. Open source only makes _finding_ trackers/malware/spyware easier. A good example of this is Microsoft's VSCode - it is filled with telemetry.

The only channel to prove whether a software is respecting user privacy or not is at runtime; and at runtime both open-source and closed source software behaves the same. For example, an open source client could at the time of deployment turn on some secret telemetry/tracker features that are otherwise not available in the code. The only way to detect these would be at runtime.

With that said, open source does make the job easier but it does not automatically mean the software is private. When in doubt, open the network tab of Chrome DevTools to see what is going on (at least on websites).

**Comment by thecodrr** [comment]
@pluja Notesnook is now fully open source at: https://github.com/streetwriters/notesnook

**Comment by pluja** [comment]
Awesome! @thecodrr will it ever be available for self-hosting?

**Comment by thecodrr** [comment]
Hey, yes it is planned. You can see the roadmap here: https://notesnook.com/roadmap

**Comment by spekulatius** [comment]
If it's open source what is stopping one to self-host @thecodrr?

**Comment by thecodrr** [comment]
> @spekulatius If it's open source what is stopping one to self-host @thecodrr?

The sync server is not yet open source. We are working on this and the code + documentation for it will be published ASAP. With that being said, there's nothing stopping one from self-hosting the client apps (not the same, obviously).

**Comment by spekulatius** [comment]
Ah okay, thanks for the clarification @thecodrr
