### ISSUE TITLE
Apple Keychain as a Password Manager?

### ISSUE THREAD

**Issue by aiquiral** [pluja/awesome-privacy#65]
I use Apple Keychain a lot but it is not listed in either "Avoid" or "Instead use". Are there any privacy concerns with Keychain? Or is it not listed because it is available for Apple products only?

**Comment by Gregor-Davies** [comment]
Well, Apple has famously opposed an FBI attempt to break into a phone. But the passwords can still be read by apple so it's really up to whether you trust apple.

**Comment by monokrome** [comment]
@Gregor-Davies ...do you have any supporting research that Apple can read the passwords? I don't know that that is true.

**Comment by aiquiral** [comment]
> But the passwords can still be read by apple so it's really up to whether you trust apple.

Apple claims that the passwords are end-to-end encrypted. 
https://support.apple.com/en-us/HT202303

**Comment by Gregor-Davies** [comment]
Here's some recent keychain hacks in the news.

https://www.wired.com/story/keysteal-apple-keychain-attack-shenanigans/

It uses the same password as your mac so if your macs hacked your passwords can be stolen

https://www.laptopmag.com/articles/mac-keychain-hack

**Comment by monokrome** [comment]
@aiquiral It's worth noting that end-to-end encryption doesn't mean the person who made the service doesn't keep their own key for being able to decrypt them at a later time.
