### ISSUE TITLE
[NSP] Stremio

### ISSUE THREAD

**Issue by aliPMPAINT** [pluja/awesome-privacy#7]
### Stremio, an alternative to Netflix
* [Stremio](https://www.stremio.com/) - Stremio is a modern media center that's a one-stop solution for your video entertainment. You discover, watch and organize video content from easy to install addons.
* **License**: MIT License
* **Why do you think this helps users privacy?**: You can stream movies/serials without getting tracked, also it's decentralized.
* **Under what section should this service be listed?**: Netflix
* **Additional comments / info**: The Github organization:
https://github.com/Stremio

**Comment by pluja** [comment]
Added!
