### ISSUE TITLE
Add LibreWolf Browser

### ISSUE THREAD

**Issue by a1300** [pluja/awesome-privacy#75]
### LibreWolf

* [LibreWolf](https://librewolf-community.gitlab.io/) - A fork of Firefox, focused on privacy, security and freedom.
* **License**: Mozilla Public License 2.0
* **Why do you think this helps users privacy?**: LibreWolf is a Firefox fork with enhanced security
* **Under what section should this service be listed?**: Browsers
* **Additional comments / info**:

**Comment by a1300** [comment]
PR: #30

**Comment by pluja** [comment]
PR #30 needs changes, I will merge once done!
