### ISSUE TITLE
Remove Ruqqus

### ISSUE THREAD

**Issue by polzon** [pluja/awesome-privacy#78]
While this site is open-source, it really should not be advocated for, or recommended. 

It's a far-right transphobic[[1](https://ruqqus.com/+CringeAnarchy/post/bmn7/study-long-term-effects-of-exposure)][[2](https://ruqqus.com/+Troomer/post/bodg/i-am-human-x)][[3](https://ruqqus.com/+Troomer/post/blpx/stunning-11-brave-11)], racist[[1](https://ruqqus.com/+CringeAnarchy/post/7vrq/follow-your-dreams)][[2](https://ruqqus.com/+Stonetoss/post/5cte/that-other-n-word)][[3](https://ruqqus.com/+Stonetoss/post/5u1z/oppression)], anti-vax/mask & covid conspiracies [[1](https://ruqqus.com/+Controlavirus/post/7te6/cience)][[2](https://ruqqus.com/+Controlavirus/post/8bkh/absolute-kings)][[3](https://ruqqus.com/+CoronavirusCirclejerk)][[4](https://ruqqus.com/+TheBureauofLitMemes/post/blfc/reprogramming-complete)], and sexist [[1](https://ruqqus.com/+BasedDepartment/post/bofr/respecc-wamen)][[2](https://ruqqus.com/+BasedMemes/post/bmd5/toxic-thots)][[3](https://ruqqus.com/+Memes/post/bltt/back-in-my-day)] website that is entirely hate-speech. 

These are not cherry-picked examples either, they are literally pulled from the front-page. You can just take a peek at the front-page of the site for yourself to verify. There's nothing redeeming about this website.

**Comment by monokrome** [comment]
One of the benefits of it being open source is that people could host their own instances if the site itself has a trash community - which is apparent. 

I think that it's a bit excessive to rate the quality or recommendation of the software itself by the quality (or in this case, lack thereof) of content that their community seems to have.

Is there something I'm missing here? Are these people that you linked the actual authors of the software itself?

Are you sure that they just don't need more help in terms of trust & safety and moderation? That's a hard problem for a small software project. In which way do these suggestions have anything to do with the software and it's authors itself?

**Comment by monokrome** [comment]
A potentially more concerning point of contention here, however, may be that the software seems to have CloudFlare's tracking technology in the header, which is directly opposed to the privacy of it's users. As you can see in the network tab, it reaches out to cloudflareinsights.com via an asynchronous request on every page.

<img width="199" alt="Screen Shot 2021-05-28 at 13 51 56" src="https://user-images.githubusercontent.com/242997/120051332-dfd50000-bfbb-11eb-8723-2045bfb6668f.png">

**Comment by monokrome** [comment]
Oh, cool. We also have the NewRelic user agent which is known to be a tracking disaster.

<img width="658" alt="Screen Shot 2021-05-28 at 14 03 15" src="https://user-images.githubusercontent.com/242997/120051731-7655f100-bfbd-11eb-83f6-413c27cd8cd6.png">

**Comment by polzon** [comment]
I do see the admins of the site encourage this speech. I don't think they consider it a problem and just consider it free speech. The lack of moderation is pretty much the entire point of the website, rather then privacy. You also don't see pro-privacy mentioned anywhere on the site or Github. The opensource aspect is mostly a bonus.

I do think when recommend a site that the community should be an important factor. You're recommending the site, rather then the platform that it's built on after all. If you go on Ruqqus, there is no avoiding its community. Maybe instead, link the to [Ruqqus Github](https://github.com/ruqqus/ruqqus) instead?

Funny enough, Ruqqus forks spawned a website that is basically the entire opposite and is a [feminist](https://thepinkpill.co/) site. There's also [this Ruqqus fork](https://rdrama.net/) which I can't tell much about what this community is about, but is kind of looks like another hatespeech site.

**Comment by pluja** [comment]
I see. I understand the concerns on what the Ruqqus community is promoting, but I also don't want to remove this as it is a Reddit alternative. I will instead link to their repo and mention this issue right after the service description.

Thanks for reporting this.

**Comment by monokrome** [comment]
@pluja what about the literal privacy issues that I brought up?

**Comment by pluja** [comment]
Thanks for this. Ruqqus is being delisted.

**Comment by pluja** [comment]
> Maybe it's time to write a bot scanning things on this list that don't respect user privacy.

@monokrome As it is stated in the [ABOUT.md](https://github.com/pluja/awesome-privacy/blob/main/misc/ABOUT.md):

> This list may contain some errors and some services may be delisted in the future after discussion. Before going for a service/app make your own investigation, take time to explore and don't trust anybody. This list is just an index of privacy-friendly apps and services but it is not a guarantee that some issues could be discovered in the future for a particular service/app.

It is me alone making the investigations for each service, and  there may be services where I mistakenly miss some things. This is why this list is collaborative and there are issues and pull requests to discuss.

**Comment by monokrome** [comment]
@pluja Yes, I understand this. I was considering writing a bot for that. I wasn't trying to feature request and/or berate anyone. If it seemed that way, I apologize for confusion. I just wanted to make sure it was clear that this is not privacy-focused. :)
