### ISSUE TITLE
[NSP] Hat.sh

### ISSUE THREAD

**Issue by sh-dv** [pluja/awesome-privacy#8]
### Hat.sh

* [Hat.sh](https://hat.sh/) - A Free, Fast, Secure and Serverless File Encryption.
* **License**: MIT License
* **Why do you think this helps users privacy?**:  Hat.sh is a opensource Javascript app that provides secure file encryption using the AES-256-GCM algorithm from the WebCryptoAPI included in your browser. it can be very useful for people who want to encrypt a file on the go, and for privacy beginners.
* **Under what section should this service be listed?**: File Encryption
* **Additional comments / info**:  files are not uploaded to a server, everything is done offline in your browser. the app is available for offline use mac/linux/windows.

**Comment by pluja** [comment]
Added!
