### ISSUE TITLE
Add Velvetyne Foundry / Fonts

### ISSUE THREAD

**Issue by IngrownMink4** [pluja/awesome-privacy#81]
### Velvetyne Type Foundry

* [Velvetyne Type Foundry](https://www.velvetyne.fr/) - VTF, or the Velvetyne Type Foundry were making fonts since 2010, they're designing and distributing free and open source typefaces. They also organise ass-kicking workshops for humans and computers.
* **License**:  SIL Open Font License (OFL)
* **Why do you think this helps users privacy?**: They're openly supporting free/libre and open source movement.
* **Under what section should this service be listed?**: Fonts
* **Additional comments / info**: I have used a few experimental typefaces and I have to say that not only are they aesthetically amazing and original, but they are also very transparent with the development and have a very good portfolio presentation.
It's also hosted in France (EU). They use Piwik (Matomo) as the main web analytics service.

**Comment by pluja** [comment]
Added in d5aa7b8858438c42748972d24e757fedafd57a11
