### ISSUE TITLE
Add [Organic Maps]/[Maps]

### ISSUE THREAD

**Issue by onupirat** [pluja/awesome-privacy#88]
### Organic Maps

* [Organic Maps](https://github.com/organicmaps/organicmaps) - Organic Maps is an Android & iOS offline maps app for travellers, tourists, hikers and cyclists based on top of crowd-sourced OpenStreetMap data.
* **License**: Apache License
* **Why do you think this helps users privacy?**: Open Source
* **Under what section should this service be listed?**: Maps and Navigation
* **Additional comments / info**: <Add any additional info here>

**Comment by Gregor-Davies** [comment]
I've added this in this pull request (https://github.com/pluja/awesome-privacy/pull/95)

Thanks for the suggestion.

**Comment by pluja** [comment]
#95 Adds this. Thank you @Gregor-Davies!
