### ISSUE TITLE
Add Petal Maps to avoid/Maps

### ISSUE THREAD

**Issue by CrossWayIstaken** [pluja/awesome-privacy#91]
### Petal Maps by Huawei

* [Petal Maps](https://consumer.huawei.com/en/mobileservices/petalmaps/) - Maps created by Huawei.
* **License**: Unknown
* **Under what section should this service be listed?**: Maps and navigation
* **Additional comments / info**: Made by a Chinese company which was suspected of *helping* the Chinese government

**Comment by Gregor-Davies** [comment]
I've made a pull request (https://github.com/pluja/awesome-privacy/pull/95) with this change.

Thanks for the suggestion.

**Comment by pluja** [comment]
#95 Adds this. Thanks to @Gregor-Davies !
